export type Language = 'en' | 'ar';

export const strings = {
  versionNumber: '1.3.2',

  en: {
    // App
    appName: 'Haweshly',
    tagline: 'Your Financial Future',

    // Tabs
    dashboard: 'Home',
    goals: 'Goals',
    analytics: 'Analytics',
    settings: 'Settings',

    // Dashboard
    totalSaved: 'Total Saved',
    activeGoals: 'Active Goals',
    overallProgress: 'Overall Progress',
    recentActivity: 'Recent Activity',
    noGoals: 'No goals yet',
    noGoalsDesc: 'Create your first financial goal to get started',
    createGoal: 'Create Goal',
    addGoal: 'Add Goal',
    favoriteGoals: 'Favorite Goals',

    // Goals
    goalName: 'Goal Name',
    targetAmount: 'Target Amount',
    startDate: 'Start Date',
    deadline: 'Deadline',
    savingsNeeded: 'Savings Needed',
    saved: 'Saved',
    remaining: 'Remaining',
    progress: 'Progress',
    daysLeft: 'Days Left',
    completed: 'Completed!',
    dailySavings: 'Daily Needed',
    weeklySavings: 'Weekly Needed',
    monthlySavings: 'Monthly Needed',
    addSavings: 'Add Savings',
    savingsHistory: 'Savings History',
    editGoal: 'Edit Goal',
    deleteGoal: 'Delete Goal',
    goalIcon: 'Goal Icon',
    tapToChangeIcon: 'Tap to change icon',
    goalNotes: 'Notes',
    goalNotesPlaceholder: 'Add notes about this goal...',
    confirmDelete: 'Confirm Delete',
    confirmDeleteMsg: 'Are you sure you want to delete this goal? All savings data will be lost.',
    confirmDeleteEntry: 'Are you sure you want to delete this savings entry?',
    cancel: 'Cancel',
    ok: 'OK',
    delete: 'Delete',
    save: 'Save',
    amount: 'Amount',
    date: 'Date',
    edit: 'Edit',
    noSavings: 'No savings entries yet',
    addFirstSaving: 'Add your first saving to track progress',

    // Analytics
    analyticsTitle: 'Analytics',
    totalDeposits: 'Total Deposits',
    totalWithdrawals: 'Total Withdrawals',
    totalGoals: 'Total Goals',
    depositEntries: 'Deposit Entries',
    avgPerDeposit: 'Avg. per Deposit',
    mostProgress: 'Most Progress',
    goalBreakdown: 'Goal Breakdown',

    // Settings
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    notifications: 'Notifications',
    remindersEnabled: 'Enable Reminders',
    reminderFrequency: 'Reminder Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    about: 'About',
    version: 'Version',

    // Validation
    required: 'This field is required',
    invalidAmount: 'Please enter a valid amount',
    invalidDate: 'Please enter a valid date',
    deadlineAfterStart: 'Deadline must be after start date',

    // Misc
    currency: 'EGP',
    of: 'of',
    day: 'day',
    days: 'days',
    noData: 'No data available',

    // Search & Filter
    searchGoals: 'Search goals...',
    filter: 'Filter',
    filterGoals: 'Filter Goals',
    sortBy: 'Sort By',
    statusFilter: 'Status',
    allGoals: 'All Goals',
    activeGoals2: 'Active',
    completedGoals2: 'Completed',
    sortNameAZ: 'Name (A → Z)',
    sortNameZA: 'Name (Z → A)',
    sortProgressHigh: 'Most Progress',
    sortProgressLow: 'Least Progress',
    sortDeadline: 'Nearest Deadline',
    sortAmountHigh: 'Highest Target',
    applyFilter: 'Apply',
    resetFilter: 'Reset',
    noResults: 'No goals match your search',
    noResultsDesc: 'Try a different search term or reset filters',

    // Recent Activity Screen
    seeMore: 'See More',
    allActivity: 'All Activity',
    filterByDate: 'Filter by Date',
    fromDate: 'From',
    toDate: 'To',
    noActivity: 'No activity yet',
    noActivityInRange: 'No activity in this date range',
    allGoalsFilter: 'All Goals',

    // Lock Screen
    createPIN: 'Create a PIN',
    confirmPIN: 'Confirm PIN',
    enterPIN: 'Enter PIN',
    welcomeBack: 'Welcome back!',
    createPINSubtitle: 'Set a 6-digit PIN to secure your Haweshly data.',
    confirmPINSubtitle: 'Re-enter your PIN to confirm.',
    enterPINSubtitle: 'Enter your 6-digit PIN to access Haweshly.',
    unlockWithFingerprint: 'Use fingerprint to unlock.',
    unlockWithFaceID: 'Use Face ID to unlock.',
    usePINInstead: 'Use PIN instead',
    useFingerprintInstead: 'Use Fingerprint instead',
    useFaceIDInstead: 'Use Face ID instead',
    pinMismatch: "PINs don't match. Please start over.",
    incorrectPIN: 'Incorrect PIN. Try again.',
    sessionExpiredTitle: 'Session Expired',
    sessionExpiredMsg: 'Your session has expired. Please authenticate again to continue.',
  },

  ar: {
    appName: 'Haweshly',
    tagline: 'مستقبلك المالي',

    dashboard: 'الرئيسية',
    goals: 'الأهداف',
    analytics: 'التحليلات',
    settings: 'الإعدادات',

    activeGoals: 'الأهداف النشطة',
    overallProgress: 'التقدم الكلي',
    recentActivity: 'النشاط الأخير',
    noGoals: 'لا توجد أهداف بعد',
    noGoalsDesc: 'أنشئ هدفك المالي الأول للبدء',
    createGoal: 'إنشاء هدف',
    addGoal: 'إضافة هدف',
    favoriteGoals: 'الأهداف المفضلة',

    goalName: 'اسم الهدف',
    targetAmount: 'المبلغ المستهدف',
    startDate: 'تاريخ البداية',
    deadline: 'الموعد النهائي',
    savingsNeeded: 'المطلوب للتوفير',
    saved: 'تم توفيره',
    remaining: 'المتبقي',
    progress: 'التقدم',
    daysLeft: 'أيام متبقية',
    completed: 'مكتمل!',
    dailySavings: 'المطلوب يومياً',
    weeklySavings: 'المطلوب أسبوعياً',
    monthlySavings: 'المطلوب شهرياً',
    addSavings: 'إضافة مدخرات',
    savingsHistory: 'سجل المدخرات',
    editGoal: 'تعديل الهدف',
    deleteGoal: 'حذف الهدف',
    goalIcon: 'أيقونة الهدف',
    tapToChangeIcon: 'اضغط لتغيير الأيقونة',
    goalNotes: 'ملاحظات',
    goalNotesPlaceholder: 'أضف ملاحظات حول هذا الهدف...',
    confirmDelete: 'تأكيد الحذف',
    confirmDeleteMsg: 'هل أنت متأكد من حذف هذا الهدف؟ ستُفقد جميع بيانات المدخرات.',
    confirmDeleteEntry: 'هل أنت متأكد من حذف هذا الإدخال؟',
    cancel: 'إلغاء',
    ok: 'حسناً',
    delete: 'حذف',
    save: 'حفظ',
    amount: 'المبلغ',
    date: 'التاريخ',
    edit: 'تعديل',
    noSavings: 'لا توجد إدخالات مدخرات بعد',
    addFirstSaving: 'أضف أول مدخراتك لتتبع التقدم',

    analyticsTitle: 'التحليلات',
    totalSaved: 'الإجمالي الان',
    totalDeposits: 'إجمالي الودائع',
    totalWithdrawals: 'إجمالي السحوبات',
    totalGoals: 'إجمالي الأهداف',
    depositEntries: 'إدخالات الودائع',
    avgPerDeposit: 'متوسط كل ودائع',
    mostProgress: 'أكثر تقدماً',
    goalBreakdown: 'تفاصيل الأهداف',

    settingsTitle: 'الإعدادات',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    notifications: 'الإشعارات',
    remindersEnabled: 'تفعيل التذكيرات',
    reminderFrequency: 'تكرار التذكير',
    daily: 'يومياً',
    weekly: 'أسبوعياً',
    monthly: 'شهرياً',
    about: 'حول التطبيق',
    version: 'الإصدار',

    required: 'هذا الحقل مطلوب',
    invalidAmount: 'يرجى إدخال مبلغ صحيح',
    invalidDate: 'يرجى إدخال تاريخ صحيح',
    deadlineAfterStart: 'يجب أن يكون الموعد النهائي بعد تاريخ البداية',

    currency: 'جنيه',
    of: 'من',
    day: 'يوم',
    days: 'أيام',
    noData: 'لا توجد بيانات',

    // Search & Filter
    searchGoals: 'ابحث عن أهداف...',
    filter: 'تصفية',
    filterGoals: 'تصفية الأهداف',
    sortBy: 'ترتيب حسب',
    statusFilter: 'الحالة',
    allGoals: 'كل الأهداف',
    activeGoals2: 'نشطة',
    completedGoals2: 'مكتملة',
    sortNameAZ: 'الاسم (أ → ي)',
    sortNameZA: 'الاسم (ي → أ)',
    sortProgressHigh: 'الأعلى تقدماً',
    sortProgressLow: 'الأقل تقدماً',
    sortDeadline: 'أقرب موعد نهائي',
    sortAmountHigh: 'أعلى مبلغ مستهدف',
    applyFilter: 'تطبيق',
    resetFilter: 'إعادة تعيين',
    noResults: 'لا توجد أهداف تطابق بحثك',
    noResultsDesc: 'جرب كلمة بحث مختلفة أو أعد تعيين الفلتر',

    // Recent Activity Screen
    seeMore: 'عرض المزيد',
    allActivity: 'كل الأنشطة',
    filterByDate: 'تصفية بالتاريخ',
    fromDate: 'من',
    toDate: 'إلى',
    noActivity: 'لا يوجد نشاط بعد',
    noActivityInRange: 'لا يوجد نشاط في هذا النطاق الزمني',
    allGoalsFilter: 'كل الأهداف',

    // Lock Screen
    createPIN: 'إنشاء رمز PIN',
    confirmPIN: 'تأكيد رمز PIN',
    enterPIN: 'أدخل رمز PIN',
    welcomeBack: 'مرحباً بعودتك!',
    createPINSubtitle: 'عيّن رمز PIN مكوناً من 6 أرقام لتأمين بياناتك.',
    confirmPINSubtitle: 'أعد إدخال رمز PIN للتأكيد.',
    enterPINSubtitle: 'أدخل رمز PIN المكون من 6 أرقام للوصول إلى Haweshly.',
    unlockWithFingerprint: 'استخدم بصمة الإصبع للفتح.',
    unlockWithFaceID: 'استخدم Face ID للفتح.',
    usePINInstead: 'استخدم رمز PIN بدلاً من ذلك',
    useFingerprintInstead: 'استخدم بصمة الإصبع بدلاً من ذلك',
    useFaceIDInstead: 'استخدم Face ID بدلاً من ذلك',
    pinMismatch: 'رمزا PIN غير متطابقَين. يرجى البدء من جديد.',
    incorrectPIN: 'رمز PIN غير صحيح. حاول مجدداً.',
    sessionExpiredTitle: 'انتهت الجلسة',
    sessionExpiredMsg: 'انتهت جلستك. يرجى تسجيل الدخول مجدداً للمتابعة.',
  },
};

export interface Category {
  label: string;
  categoryIcon: string; // FA icon name shown in the category tab
  icons: string[];      // FA icon name strings shown in the picker grid
}

export const CATEGORIES: Category[] = [
  {
    label: 'Accessories',
    categoryIcon: 'faGlasses',
    icons: [
      'faGlasses',
      'faClock',
      'faRing',
      'faGem',
      'faBagShopping',
      'faFaceSmile',
      'faHatCowboy',
      'faShirt',
      'faShoePrints',
      'faStar'
    ],
  },
  {
    label: 'Bills',
    categoryIcon: 'faReceipt',
    icons: ['faLightbulb', 'faDroplet', 'faFire', 'faMobile', 'faGlobe', 'faHouse', 'faReceipt', 'faCreditCard', 'faEnvelope', 'faFile'],
  },
  {
    label: 'Debts',
    categoryIcon: 'faMoneyBillTransfer',
    icons: ['faMoneyBillTransfer', 'faArrowTrendDown', 'faReceipt', 'faCreditCard', 'faBuilding', 'faCalendar', 'faTriangleExclamation', 'faFile', 'faArrowsRotate', 'faMoneyBillWave'],
  },
  {
    label: 'Donations',
    categoryIcon: 'faHandHoldingHeart',
    icons: [
      'faHandHoldingHeart',
      'faHeart',
      'faHandHoldingDollar',
      'faHandsHelping',
      'faPeopleCarry',
      'faMosque',
      'faChurch',
      'faSeedling',
      'faGift',
      'faCoins'
    ],
  },
  {
    label: 'Education',
    categoryIcon: 'faGraduationCap',
    icons: ['faBook', 'faGraduationCap', 'faPencil', 'faSchool', 'faMicroscope', 'faLightbulb', 'faBookOpen', 'faPaintbrush', 'faFlask', 'faCalculator'],
  },
  {
    label: 'Entertainment',
    categoryIcon: 'faFilm',
    icons: ['faFilm', 'faGamepad', 'faMusic', 'faMasksTheater', 'faGuitar', 'faCakeCandles', 'faTv', 'faHeadphones', 'faCamera', 'faGift'],
  },
  {
    label: 'Family',
    categoryIcon: 'faPeopleRoof',
    icons: ['faPeopleRoof', 'faBaby', 'faDog', 'faCat', 'faRing', 'faChurch', 'faHandshake', 'faPeopleGroup', 'faHeartPulse', 'faHouseChimney'],
  },
  {
    label: 'Food',
    categoryIcon: 'faUtensils',
    icons: ['faBurger', 'faPizzaSlice', 'faDrumstickBite', 'faUtensils', 'faBowlFood', 'faMugHot', 'faLeaf', 'faCarrot', 'faCookie', 'faAppleWhole'],
  },
  {
    label: 'Goals',
    categoryIcon: 'faBullseye',
    icons: ['faBullseye', 'faTrophy', 'faStar', 'faRocket', 'faCalendarDays', 'faMoneyBill', 'faChartBar', 'faFire', 'faLightbulb', 'faWandMagicSparkles'],
  },
  {
    label: 'Health',
    categoryIcon: 'faHeart',
    icons: ['faHeart', 'faPills', 'faHospital', 'faDumbbell', 'faPersonRunning', 'faAppleWhole', 'faSpa', 'faHandSparkles', 'faStethoscope', 'faSyringe'],
  },
  {
    label: 'Income',
    categoryIcon: 'faMoneyBillWave',
    icons: ['faMoneyBillWave', 'faMoneyBill', 'faBuilding', 'faArrowTrendUp', 'faBriefcase', 'faReceipt', 'faChartBar', 'faCoins', 'faCreditCard', 'faTrophy'],
  },
  {
    label: 'Investment',
    categoryIcon: 'faArrowTrendUp',
    icons: ['faArrowTrendUp', 'faChartBar', 'faChartLine', 'faBuilding', 'faCoins', 'faGem', 'faArrowTrendDown', 'faMobile', 'faMoneyBill', 'faNewspaper'],
  },
  {
    label: 'Personal Care',
    categoryIcon: 'faSpa',
    icons: ['faSpa', 'faHandSparkles', 'faPumpSoap', 'faScissors', 'faShower', 'faEye', 'faFaceSmile', 'faHeart', 'faGem', 'faStar'],
  },
  {
    label: 'Pets',
    categoryIcon: 'faPaw',
    icons: ['faDog', 'faCat', 'faPaw', 'faBone', 'faSyringe', 'faHospital', 'faHeart', 'faFishFins', 'faOtter', 'faLeaf'],
  },
  {
    label: 'Rent',
    categoryIcon: 'faHouse',
    icons: ['faHouse', 'faKey', 'faMoneyBillWave', 'faFile', 'faBuilding', 'faReceipt', 'faCalendar', 'faCreditCard', 'faHouseChimney', 'faFileLines'],
  },
  {
    label: 'Savings',
    categoryIcon: 'faPiggyBank',
    icons: ['faBuilding', 'faPiggyBank', 'faCoins', 'faArrowTrendUp', 'faChartBar', 'faBullseye', 'faGem', 'faLock', 'faStar', 'faCalendarDays'],
  },
  {
    label: 'Shopping',
    categoryIcon: 'faCartShopping',
    icons: ['faCartShopping', 'faBagShopping', 'faStore', 'faBox', 'faTag', 'faGift', 'faCreditCard', 'faReceipt', 'faShirt', 'faPersonWalking'],
  },
  {
    label: 'Subscriptions',
    categoryIcon: 'faArrowsRotate',
    icons: [
      'faArrowsRotate',
      'faGamepad',
      'faSpotify',
      'faYoutube',
      'faAmazon',
      'faApple',
      'faTiktok',
      'faFacebook',
      'faTwitter',
      'faInstagram',
      "faLinkedin",
      "faSnapchat",
      "faPinterest",
      "faMicrosoft",
      "faDiscord"
    ],
  },
  {
    label: 'Tech',
    categoryIcon: 'faLaptop',
    icons: ['faLaptop', 'faMobile', 'faGamepad', 'faCamera', 'faHeadphones', 'faDesktop', 'faTv', 'faMicrophone', 'faBatteryFull', 'faClock'],
  },
  {
    label: 'Transport',
    categoryIcon: 'faCar',
    icons: ['faCar', 'faBus', 'faTrainSubway', 'faGasPump', 'faMotorcycle', 'faBicycle', 'faPlane', 'faShip', 'faTruck', 'faPersonWalking'],
  },
  {
    label: 'Travel',
    categoryIcon: 'faPlane',
    icons: ['faPlane', 'faUmbrellaBeach', 'faSailboat', 'faTent', 'faMap', 'faSuitcaseRolling', 'faShip', 'faTrain', 'faHotel', 'faCompass'],
  },
  {
    label: 'Transfers',
    categoryIcon: 'faArrowRightArrowLeft',
    icons: ['faArrowsRotate', 'faBuilding', 'faCreditCard', 'faMobile', 'faMoneyBillWave', 'faMoneyBill', 'faCoins', 'faArrowRightArrowLeft', 'faPercent', 'faShieldHalved'],
  },
];
